[package]
name = "ms-app-state"
version = "0.1.0"
edition = "2021"

[dependencies]
ms-common = { path = "../common" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
