[package]
name = "ms-mux"
version = "0.1.0"
edition = "2021"

[dependencies]
ms-common = { path = "../common" }
thiserror = { workspace = true }
tracing = { workspace = true }
byteorder = { workspace = true }
